BreakoutSite/BreakoutSite/Controllers/BookingController.cs
using BreakoutSite.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BreakoutSite.Controllers
{
    public class BookingController : Controller
    {
        private string strResult;
        private int intResult;
        // GET: Booking
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(ProfileModel model, BookingModel book)
        {
            using (SqlConnection con = new SqlConnection("Server=breakout-dc-1\\SQLEXPRESS;Database=BreakOutDB;User ID=break;Password=password123"))
            {
                using (SqlCommand command = new SqlCommand("SELECT ID FROM UserPass_Tab WHERE (Username = @User)"))
                {
                    command.Connection = con;
                    con.Open();
                    command.Parameters.AddWithValue("@User", ProfileModel.DisplayName);
                    SqlDataReader dr = command.ExecuteReader();
                    while (dr.Read())
                    {
                        strResult = dr[0].ToString();
                        intResult = int.Parse(strResult);
                    }
                    con.Close();
                }
                using (SqlCommand update = new SqlCommand("INSERT INTO Booking_Tab(ID, Date, Place) VALUES(@ID, @DATE, @PLACE)"))
                {
                    update.Connection = con;
                    con.Open();
                    update.Parameters.AddWithValue("@ID", intResult);
                    update.Parameters.AddWithValue("@DATE", book.BookDate);
                    update.Parameters.AddWithValue("@PLACE", book.BookPlace);
                    ProfileModel.HasBooking = true;
                    update.ExecuteNonQuery();
                }
            }
            return View();
        }
    }
}

BreakoutSite/BreakoutSite/Views/Booking/Index.cshtml
@model BreakoutSite.Models.BookingModel

@{
    ViewBag.Title = "Bookings";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    @using (Html.BeginForm("Index", "Booking", FormMethod.Post))
    {
        <p>Date Wanted: </p> @Html.TextBoxFor(m => m.BookDate)
        <p>Place Wanted: </p> @Html.TextBoxFor(m => m.BookPlace)
        <input type="submit" value="Submit" />
    }
</body>
</html>

